FROM node:latest

WORKDIR /usr/src/app
COPY package.json .

RUN npm install
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list
RUN apt-get update && apt-get install --no-install-recommends -y google-chrome-stable

COPY . .

CMD ["npm", "run", "start"]